spring:
  application:
    name: openai
  jpa:
    hibernate:
      ddl-auto: update
  # Database Configuration (PostgreSQL/Neon)
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name:
    hikari:
      max-lifetime: 180000 # 3 minutes (Neon's default idle timeout is usually 5 mins)
      keepalive-time: 60000 # 1 minute
      connection-timeout: 30000
      validation-timeout: 5000

  # H2 Console (for local testing)
  h2:
    console:
      enabled: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
      embedding:
        model: text-embedding-3-small

    # Vector DB Config (Pinecone)
    vectorstore:
    # PINECOME: For General RAG Knowledge
#      pinecone:
#        api-key: ${PINECONE_API_KEY}
#        index-name: rag-index
#        environment: us-east-1
#        host: https://rag-index-mjk67eq.svc.aped-4627-b74a.pinecone.io
      pgvector:
        table-name: semantic_cache
        dimensions: 1536
        initialize-schema: false
        index-type: hnsw

    mcp:
      client:
        enabled: true
        stdio:
          connections:
            github:
              command: C:\Users\PrateekGupta\AppData\Roaming\npm\mcp-server-github.cmd
              args: []

              env:
                GITHUB_PERSONAL_ACCESS_TOKEN: ${GITHUB_PAT}
        toolcallback:
          enabled: true



logging:
  level:
    root: INFO
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
          vectorstore: DEBUG
server:
  port: ${PORT:8080}